# Generated by Django 2.0.7 on 2020-05-03 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0004_course_course_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_taken',
            name='taken',
            field=models.ManyToManyField(related_name='c_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course_taken',
            name='user',
            field=models.ManyToManyField(related_name='c_user', to='Flights.Course'),
        ),
    ]
